### ISSUE TITLE
按照 教程做下来 error

### ISSUE THREAD

**Issue by wulisensen** [arronf2e/Vue2.0LOL#1]
![image](https://cloud.githubusercontent.com/assets/22022130/23496335/901872cc-ff58-11e6-9fd3-69203cc8ed23.png)

**Comment by arronf2e** [comment]
@wulisensen 稍等，这个代理我后来没用到，我更新一下

**Comment by arronf2e** [comment]
@wulisensen 重新更新下代码

**Comment by wulisensen** [comment]
@arronf2e 还是 有很多模块没找到
![image](https://cloud.githubusercontent.com/assets/22022130/23496720/9cdcf4a4-ff5a-11e6-8cb1-e99336b36a56.png)
是不是没有安装到依赖中

**Comment by arronf2e** [comment]
@wulisensen 你用cnpm的吗 ？ 换npm 试试

**Comment by arronf2e** [comment]
@wulisensen 使用npm没有问题，cnpm的话会漏一些包，自己按提示装一下

**Comment by wulisensen** [comment]
@arronf2e   可以了 谢谢解决了我的问题  原来cnpm还有这个坑。。那平时用的话 如果包很多岂不是要 下载半天。。。。

**Comment by arronf2e** [comment]
@wulisensen 是的，之前我就被cnpm坑过-，-
