### ISSUE TITLE
视频页渲染要花10秒！

### ISSUE THREAD

**Issue by Gaohaoyang** [arronf2e/Vue2.0LOL#2]
vue性能这么差吗？

**Comment by arronf2e** [comment]
不是，一个视频加载一个iframe，很卡，接口就是这样，很尴尬

**Comment by arronf2e** [comment]
@Gaohaoyang 和vue没关系 。。

**Comment by ChuckCZC** [comment]
@arronf2e 应该可以用正则把接口的视频地址取出来，直接用video，不要设定src，直接用封面图就行了，人家点击时再动态设定该video的src

**Comment by arronf2e** [comment]
@ChuckCZC OK，谢谢提醒，这个我会在后续更新掉，确实很卡

**Comment by Gaohaoyang** [comment]
建议视频列表页使用 **静态图片** 做为封面。

用户点击后单独跳转到视频播放页。

一屏里面播放这么多视频是不合理的

**Comment by arronf2e** [comment]
@Gaohaoyang 明白，正在优化，用正则把iframe的src取出来作为链接

**Comment by Gaohaoyang** [comment]
加油

**Comment by arronf2e** [comment]
@Gaohaoyang OK
