### ISSUE TITLE
请教下

### ISSUE THREAD

**Issue by jl1014171068** [arronf2e/Vue2.0LOL#4]
请问在news下面的文章页面除了使用后台传地址的方式去做，如果用vue的方式来做有什么思路呢？html-template-plugin 还有什么方式呢？
新手...做到这块卡住了

**Comment by arronf2e** [comment]
不是很明白您的意思呢，我现在news的数据是本地的，没有通过接口请求

**Comment by jl1014171068** [comment]
news 下面的文章列表--内容页面   ，现在内容页面是直接用的data里面的article_url 外链地址，如果内容页面用vue来实现，如何解决地址问题呢......

**Comment by arronf2e** [comment]
定义url，把新闻列表中的每条新闻的唯一ID，作为路由的参数带过去，然后在详情页获取路由中的参数请求相应的详情页

**Comment by arronf2e** [comment]
和我英雄列表页 => 英雄详情页一样

**Comment by jl1014171068** [comment]
好吧，我试试，谢谢您的解答。
