### ISSUE TITLE
搜索页面

### ISSUE THREAD

**Issue by leixiaojuan** [arronf2e/Vue2.0LOL#5]
搜索页面数据数据是没反应的，很多页面没有

**Comment by arronf2e** [comment]
我都正常呢，有时候可能是接口太慢导致的

**Comment by liangbijie** [comment]
@leixiaojuan 应该是输入中文，导致接口报错，如果你输入英文应该就会加载出来了

**Comment by arronf2e** [comment]
@liangbijie   我一直都用中文
