### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by liangbijie** [arronf2e/Vue2.0LOL#6]
我下载你的项目，然后install运行后，报错误，很多模块没有依赖下来，请问该怎么解决？

**Comment by arronf2e** [comment]
推荐npm  i  ，cnpm可能会漏包，如果你用cnpm的话，就手动装一下漏的包，嘿嘿

**Comment by liangbijie** [comment]
@arronf2e 谢谢了~问题已经解决了，刚才我看了下用cnpm下载下来的依赖全部是空文件
