### ISSUE TITLE
带玩游戏平台的请求结果

### ISSUE THREAD

**Issue by serrt** [arronf2e/Vue2.0LOL#8]
我的请求结果是这个
`无法将类型为“Newtonsoft.Json.Linq.JObject”的对象强制转换为类型“Newtonsoft.Json.Linq.JArray`
怎么回事

**Comment by arronf2e** [comment]
@serrt 目前他们平台的接口在调整，要等两天，不好意思哈

**Comment by serrt** [comment]
哦，谢谢
