### ISSUE TITLE
win下 fsevent无法使用，没法好好玩耍了

### ISSUE THREAD

**Issue by kookChen** [arronf2e/Vue2.0LOL#9]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fseven ts):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN muse-ui@2.0.0-rc.5 requires a peer of keycode@^2.1.7 but none was installed.

win下面挂了，这只能mac呢，撸主能不能弄个win下面也可以玩的

**Comment by arronf2e** [comment]
npm cache clear
npm install --no-optional
这样试一下呢

**Comment by kookChen** [comment]
This dependency was not found:
* mint-ui in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/player.vue
To install it, you can run: npm install --save mint-ui

按照撸主的做法，mac那个选项是没有提示了，但是本项目不是用的 muse-ui吗？ 怎么会提示要安装饿了么的ui呢，有点尴尬...

**Comment by arronf2e** [comment]
@kookChen   不科学啊，我依赖都删啦

**Comment by kookChen** [comment]
撸主，今天在公司又装了一次，先
npm cache clear
npm install --no-optional
然后提示
npm WARN muse-ui@2.0.0-rc.5 requires a peer of keycode@^2.1.7 but none was installed.
然后再
npm install keycode@^2.1.7 --save --no-optional
然后又提示要装昨晚那个mint-ui
装完后终于好了.......
真是要好事多麿啊

**Comment by arronf2e** [comment]
不应该唉，我早上自己重新装了一下，也没提示要装mint-ui呀，你代码是不是不是最新版的@kookChen

**Comment by kookChen** [comment]
都是下载最新zip哦

**Comment by arronf2e** [comment]
@kookChen 好吧-，-
